# Generated by Django 4.0.5 on 2022-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmodel',
            name='aes_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
