# Generated by Django 4.0.5 on 2022-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
